import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const onestBold = localFont({
  src: "./fonts/OnestBold.woff",
  variable: "--font-onest-bold",
  weight: "100 900",
});
const onestRegular = localFont({
  src: "./fonts/OnestRegular.woff",
  variable: "--font-onest-regular",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${onestRegular.variable} ${onestBold.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
